luogulite_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user

luogulite_problem:
    resource: "@ProblemBundle/Controller/ProblemController.php"
    type:     annotation
    prefix:   /problem

luogulite_fos_authentication:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /authentication

luogulite_homepage:
    resource: '@HomePageBundle/Controller/HomePageController.php'
    type:     annotation
    prefix:   /

luogulite_admin_problem:
    resource: "@ProblemBundle/Controller/ProblemAdminController.php"
    type:     annotation
    prefix:   /admin/problem